name: CI - Inventory Management (MSSQL on Ubuntu)

on:
  push:
    branches:
      - release-MSSQL
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/**'

jobs:
  build-and-test:
    name: Build and Test (.NET with Docker SQL Server)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Start SQL Server in Docker
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrong!Passw0rd" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Install sqlcmd tools
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            if /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "SELECT 1" &> /dev/null; then
              echo "SQL Server is up!"
              break
            fi
            echo "Waiting for SQL Server..."
            sleep 2
          done

      - name: Create InventoryDB and Products table
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q "CREATE DATABASE InventoryDB;"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -d InventoryDB -Q "CREATE TABLE Products (Id INT PRIMARY KEY IDENTITY, Name NVARCHAR(100), Quantity INT, Price FLOAT);"

      - name: Restore dependencies
        run: dotnet restore MainCode/InventoryManagment.sln

      - name: Build project
        run: dotnet build MainCode/InventoryManagment.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test MainCode/InventoryManagment.sln --verbosity normal
